### 1.	Create a python program to find duplicate files by content. User will input path and it will scan all directories, sub-directories to find all duplicates files.Delete the found duplicate file.  [Hint: use hashlib]


In [6]:
import os
import hashlib

def find_duplicate_files(path):
    # dictionary to store file paths and their corresponding hashes
    hashes = {}
    duplicates = []
# walk through all the directories and subdirectories
    for root, dirs, files in os.walk(path):
        for file in files:
            # get the full path of the file
            file_path = os.path.join(root, file)

            # calculate the hash of the file contents
            with open(file_path, 'rb') as f:
                file_hash = hashlib.md5(f.read()).hexdigest()

            # if the hash already exists in the dictionary, add it to the list of duplicates
            if file_hash in hashes:
                duplicates.append((file_path, hashes[file_hash]))
            else:
                hashes[file_hash] = file_path

    return duplicates

def delete_duplicates(duplicates):
    for duplicate in duplicates:
        # print the duplicates before deleting
        print(f'Deleting {duplicate[0]} (duplicate of {duplicate[1]})')

        # delete the duplicate file
        os.remove(duplicate[0])

if __name__ == '__main__':
    path = input('Enter the path to search for duplicates: ')
    duplicates = find_duplicate_files(path)

    if duplicates:
        print(f'{len(duplicates)} duplicate files found:')
        for duplicate in duplicates:
            print(f'{duplicate[0]} (duplicate of {duplicate[1]})')

        delete = input('Do you want to delete the duplicates? (y/n): ')
        if delete.lower() == 'y':
            delete_duplicates(duplicates)
            print('Duplicates deleted successfully!')
        else:
            print('Duplicates not deleted.')
    else:
        print('No duplicate files found.')


Enter the path to search for duplicates: D:\n
1 duplicate files found:
D:\n\text1.txt (duplicate of D:\n\text.txt)
Do you want to delete the duplicates? (y/n): y
Deleting D:\n\text1.txt (duplicate of D:\n\text.txt)
Duplicates deleted successfully!


### 2.Generate random Password with exact length = 6, with minimum 1 uppercase, 2 lowercase, 2 digits, and remaining special characters. Using these packages [random, strings]


In [8]:
import random
import string
def password(length):
    
    dc=string.digits
    uc=string.ascii_uppercase
    lc=string.ascii_lowercase
    sc= string.punctuation
    
    result1=''.join(random.choice(uc)for i in range(1))
    result2=''.join(random.choice(lc)for i in range(2))
    result3=''.join(random.choice(dc)for i in range(2))
    result4=''.join(random.choice(sc)for i in range(1))
    resultpassword=result1+result2+result3+result4
    resultpassword=''.join(random.sample(resultpassword,len(resultpassword)))
    print("random password= ",resultpassword)
    
print(password(6))

random password=  <Fn6a4
None


### 3. Create 2D array and update the same 2D array provided that every prime number position should be replaced by cube of the positioned number.

In [41]:
import numpy as np

def prime(a):
    c=0
    for i in range(1,a):
        if a%i==0:
            c+=1
    if c==1:
        return True
    else:
        return False
 
def solution(arr_1,x,y):
    k=0
    for i in range(x):
        for j in range(y):
            
            if prime(k)==True:
                arr_1[i,j]=(k)**3
            k+=1
    return arr_1

x=int(input('enter the rows'))
y=int(input('enter the columns'))
arr_1=np.ones((x,y),dtype='int')
mat=solution(arr_1,x,y)
print(mat)

enter the rows6
enter the columns6
[[    1     1     8    27     1   125]
 [    1   343     1     1     1  1331]
 [    1  2197     1     1     1  4913]
 [    1  6859     1     1     1 12167]
 [    1     1     1     1     1 24389]
 [    1 29791     1     1     1     1]]


### 4. Python program to get the sum of every cubed value and its previous integer. 

In [47]:
import numpy as np

def prime(a):
    c=0
    for i in range(1,a):
        if a%i==0:
            c+=1
    if c==1:
        return True
    else:
        return False
 
def solution(arr_1,x,y):
    k=0
    for i in range(x):
        for j in range(y):
            
            if prime(k)==True:
                arr_1[i,j]=(k)**3
            k+=1
    return arr_1

x=int(input('enter the rows'))
y=int(input('enter the columns'))
#arr_1=np.ones((x,y),dtype='int')
arr_1=np.arange((x*y)).reshape(x,y)
mat=solution(arr_1,x,y)
print(mat)

enter the rows6
enter the columns6
[[    0     1     8    27     4   125]
 [    6   343     8     9    10  1331]
 [   12  2197    14    15    16  4913]
 [   18  6859    20    21    22 12167]
 [   24    25    26    27    28 24389]
 [   30 29791    32    33    34    35]]


### 5.	Given two arrays, find their intersection. Examples:

Input:  arr1[] = [1, 3, 4, 5, 7]
             arr2[] = [2, 3, 5, 6]


In [13]:
arr_1=[1,3,4,5,7]
arr_1=set(arr_1)
arr_2=[2,3,5,6]
arr_2=set(arr_2)

arr3 = arr_1.intersection(arr2)
print(arr3)

{3, 5}


### 6.	Create a 7 x 7  2D array having only multiples of 7. And return the last element of the same.

In [15]:
arr3=np.arange(7,(7**3)+1,7).reshape(7,7)

print(arr3)
print(arr3[6][6])

[[  7  14  21  28  35  42  49]
 [ 56  63  70  77  84  91  98]
 [105 112 119 126 133 140 147]
 [154 161 168 175 182 189 196]
 [203 210 217 224 231 238 245]
 [252 259 266 273 280 287 294]
 [301 308 315 322 329 336 343]]
343


###  7.	Checker Board Patten using Numpy:
    [1   0   1   0   1   0   1

    0   1   0   1   0   1   0
    
    1   0   1   0   1   0   1
    
    0   1   0   1   0   1   0
    
    1   0   1   0   1   0   1  ]


In [18]:
arr2=np.ones((7,7),dtype='int8')
arr2[1::2,::2]=0
arr2[::2,1::2]=0
arr2

array([[1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1]], dtype=int8)

### 8.	Create a given Matrix:
[  A,     B,     C,       D
E,      F,     G,       H
I,      a,      K,       L
M,    N,     o,       P
Q,     R,      S,       T
U,     0,     W,      O ]

Replace all the vowels by np.nan
A, E, I, O U  -- >  np.nan
Return the count of the missing values


In [22]:
#8
# create the matrix as a list of lists
l1 = [['A', 'B', 'C', 'D'],
       ['E', 'F', 'G', 'H'],
       ['I', 'a', 'K', 'L'],
       ['M', 'N', 'o', 'P'],
       ['Q', 'R', 'S', 'T'],
       ['U', '0', 'W', 'O']]

# define vowels to replace with None
vowels = ['A', 'E', 'I', 'O', 'U', 'a', 'o']

# replace vowels with None
for i in range(len(l1)):
    for j in range(len(l1[i])):
        if l1[i][j] in vowels:
            l1[i][j] = None

# count missing values
count_none = sum(1 for row in l1 for val in row if val is None)

print(l1)

print("Number of missing values:", count_none)


[[None, 'B', 'C', 'D'], [None, 'F', 'G', 'H'], [None, None, 'K', 'L'], ['M', 'N', None, 'P'], ['Q', 'R', 'S', 'T'], [None, '0', 'W', None]]
Number of missing values: 7
